name: 'wix_ta'
version: '1.0.0'

profile: 'wix_ta'

model-paths: ["models"]
# analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  wix_ta:
    staging:
      schema: staging_schema
      +materialized: view
    intermediate:
      schema: intermediate_schema
      +materialized: view
    warehouse:
      schema: warehouse_schema
      +materialized: table
    marts:
      schema: marts_schema
      +materialized: view

vars:
  execution_date: '2024-05-03'
  surrogate_key_treat_nulls_as_empty_strings: True
